from fastapi import APIRouter, Request, Depends, Response
from sqlalchemy.orm import Session
from app.database import get_db
from app.repositories.patient_repository import PatientRepository
from app.repositories.call_log_repository import CallLogRepository
from app.config.settings import settings

router = APIRouter(
    prefix="/voice",
    tags=["voice"]
)

@router.post("/instruct")
async def voice_instruct(request: Request, db: Session = Depends(get_db)):
    form_data = await request.form()
    
    session_id = form_data.get("sessionId")
    caller_number = form_data.get("callerNumber", "")
    dtmf_digits = form_data.get("dtmfDigits")
    direction = form_data.get("direction")
    destination_number = form_data.get("destinationNumber", "")
    
    # In Outbound calls generated by AT, the patient's number represents either the dialed destination
    # or the caller depending on how the webhook fires (usually destination for outbound API calls).
    # We fallback to callerNumber for inbound tests as well.
    patient_phone = destination_number if direction == "Outbound" else caller_number
    # Sometimes '+' is stripped via form-data mapping, ensure safety query
    if not patient_phone.startswith('+'):
        patient_phone = '+' + patient_phone.lstrip()

    patient_repo = PatientRepository(db)
    call_log_repo = CallLogRepository(db)
    
    # Need to fuzzy match or exactly match based on saved phone number format
    patient = patient_repo.get_by_phone(patient_phone)
    if not patient:
        xml_response = f"""<?xml version="1.0" encoding="UTF-8"?>
        <Response>
            <Say>Sorry, we could not find your precise medical record in our system. Goodbye.</Say>
        </Response>"""
        return Response(content=xml_response, media_type="application/xml")
    
    # Create an initial log if none exists when first instructed
    if not dtmf_digits:
        # Protect against dupes safely
        call_log_repo.create(patient.id, session_id, "active")
        
    language = patient.language.lower()
    
    # Handle user interaction
    if dtmf_digits:
        if dtmf_digits == "1":
            call_log_repo.update_adherence(session_id, adherence_status="taken")
            msg = "Thank you. Your record is updated. Goodbye." if language == "english" else "Asante. Rekodi yako imesasishwa. Kwaheri."
            xml_response = f"""<?xml version="1.0" encoding="UTF-8"?>
            <Response>
                <!-- <Play url="{settings.base_url}/static/audio/{language}/thank_you.mp3" /> -->
                <Say>{msg}</Say>
            </Response>"""
            return Response(content=xml_response, media_type="application/xml")
        elif dtmf_digits == "2":
            call_log_repo.update_adherence(session_id, adherence_status="not_taken")
            msg = "Please remember to take your medication. Thank you. Goodbye." if language == "english" else "Tafadhali kumbuka kumeza dawa zako. Asante. Kwaheri."
            xml_response = f"""<?xml version="1.0" encoding="UTF-8"?>
            <Response>
                <!-- <Play url="{settings.base_url}/static/audio/{language}/thank_you.mp3" /> -->
                <Say>{msg}</Say>
            </Response>"""
            return Response(content=xml_response, media_type="application/xml")
        elif dtmf_digits == "3":
            call_log_repo.update_adherence(session_id, adherence_status="side_effects")
            msg = "A nurse will contact you shortly about the side effects. Goodbye." if language == "english" else "Nesi atawasiliana na wewe hivi karibuni. Kwaheri."
            xml_response = f"""<?xml version="1.0" encoding="UTF-8"?>
            <Response>
                <!-- <Play url="{settings.base_url}/static/audio/{language}/thank_you.mp3" /> -->
                <Say>{msg}</Say>
            </Response>"""
            return Response(content=xml_response, media_type="application/xml")
        # If '0' or unrecognized, fall through to repeat prompts
        
    # Send prompts
    if language == "swahili":
        greeting = f"Hujambo {patient.name}."
        reminder = "Huu ni ukumbusho wako wa kila siku wa kumeza dawa."
        education = "Kumeza dawa zako kila siku ni muhimu kwa afya yako. Tafadhali zingatia."
        prompt = "Je, umemeza dawa zako leo? Bonyeza moja kwa ndio, mbili kwa hapana, tatu ikiwa una madhara yoyote, au sufuri kurudia."
    else:
        greeting = f"Hello {patient.name}."
        reminder = "This is your daily medication reminder."
        education = "Taking your medication daily is vital for your health and wellbeing."
        prompt = "Have you taken your medication today? Press 1 for yes, 2 for no, 3 for side effects, or 0 to repeat."
        
    xml_response = f"""<?xml version="1.0" encoding="UTF-8"?>
    <Response>
        <!-- Placeholders for actual audio pre-recorded prompts -->
        <!-- <Play url="{settings.base_url}/static/audio/{language}/greeting.mp3" /> -->
        <!-- <Play url="{settings.base_url}/static/audio/{language}/reminder.mp3" /> -->
        <!-- <Play url="{settings.base_url}/static/audio/{language}/education.mp3" /> -->
        <Say>{greeting}</Say>
        <Say>{reminder}</Say>
        <Say>{education}</Say>
        <GetDigits timeout="10" numDigits="1" callbackUrl="{settings.base_url}/voice/instruct">
            <!-- <Play url="{settings.base_url}/static/audio/{language}/menu_prompt.mp3" /> -->
            <Say>{prompt}</Say>
        </GetDigits>
    </Response>"""
    return Response(content=xml_response, media_type="application/xml")

@router.post("/events")
async def voice_events(request: Request, db: Session = Depends(get_db)):
    form_data = await request.form()
    
    session_id = form_data.get("sessionId")
    call_session_state = form_data.get("callSessionState") # e.g., Completed, Failed, Rejected
    
    if session_id and call_session_state:
        call_log_repo = CallLogRepository(db)
        # Update the general state of the whole call logically
        call_log_repo.update_adherence(session_id, adherence_status=None, call_status=call_session_state)
        
    # Return 200 plain text per AT schema 
    return Response(content="success", media_type="text/plain")
